interface FilterPanelProps {
  calculi: Array<number | null>;
  relationTypes: string[];
  schools: string[];
  enabledCalculi: Array<number | null>;
  enabledRelations: string[];
  selectedSchools: string[];
  minimumWeight: number;
  showAiHypotheses: boolean;
  onToggleCalculus: (value: number | null) => void;
  onToggleRelation: (value: string) => void;
  onToggleSchool: (value: string) => void;
  onMinimumWeightChange: (value: number) => void;
  onToggleAiHypotheses: () => void;
  onReset: () => void;
}

export function FilterPanel({
  calculi,
  relationTypes,
  schools,
  enabledCalculi,
  enabledRelations,
  selectedSchools,
  minimumWeight,
  showAiHypotheses,
  onToggleCalculus,
  onToggleRelation,
  onToggleSchool,
  onMinimumWeightChange,
  onToggleAiHypotheses,
  onReset,
}: FilterPanelProps) {
  return (
    <aside className="filter-panel">
      <div className="filter-panel__intro">
        <p className="eyebrow">Constellation</p>
        <h1>Genesis Architecture</h1>
      </div>

      <section>
        <h2>Calculus Era</h2>
        <div className="filter-grid">
          {calculi.map((value) => (
            <label key={String(value)} className="check-row">
              <input
                type="checkbox"
                checked={enabledCalculi.some((item) => item === value)}
                onChange={() => onToggleCalculus(value)}
              />
              <span>{value === null ? "Unknown" : `Era ${value}`}</span>
            </label>
          ))}
        </div>
      </section>

      <section>
        <h2>Relations</h2>
        <div className="filter-stack">
          {relationTypes.map((relation) => (
            <label key={relation} className="check-row">
              <input
                type="checkbox"
                checked={enabledRelations.includes(relation)}
                onChange={() => onToggleRelation(relation)}
              />
              <span>{relation.replace(/_/g, " ")}</span>
            </label>
          ))}
        </div>
      </section>

      <section>
        <h2>Minimum Weight</h2>
        <label className="range-row">
          <input
            type="range"
            min="0"
            max="1"
            step="0.05"
            value={minimumWeight}
            onChange={(event) => onMinimumWeightChange(Number(event.target.value))}
          />
          <span>{minimumWeight.toFixed(2)}</span>
        </label>
      </section>

      <section>
        <h2>Pipeline Output</h2>
        <label className="check-row">
          <input type="checkbox" checked={showAiHypotheses} onChange={onToggleAiHypotheses} />
          <span>Show AI hypotheses</span>
        </label>
        <p className="filter-panel__note">
          AI hypothesis edges are generated by the pipeline and not yet adjudicated. Off by default.
        </p>
      </section>

      <section>
        <h2>Schools</h2>
        <div className="school-list">
          {schools.slice(0, 80).map((school) => (
            <label key={school} className="check-row">
              <input
                type="checkbox"
                checked={selectedSchools.includes(school)}
                onChange={() => onToggleSchool(school)}
              />
              <span>{school}</span>
            </label>
          ))}
        </div>
      </section>

      <button className="reset-button" type="button" onClick={onReset}>
        Reset filters
      </button>
    </aside>
  );
}
